### ISSUE TITLE
Error while running sdfExport.FCmacro

### ISSUE THREAD

**Issue by suraj2596** [maidenone/RobotCreator#8]
`writing to file/home/suraj/.gazebo/models/testing/testing.sdf
b_sicissor_unit_001_
b_sicissor_unit_001_001
circularEdge_001
circularEdge_001_mirror
Joint
Joint: Joint with label Joint detected!
Traceback (most recent call last):
  File "/home/suraj/.FreeCAD/Mod/RobotCreator/Macros/sdfExport.FCMacro", line 63, in <module>
    sdfFile.write(' <joint name="'+bodyLabelFromObjStr(obj.Parent)+bodyLabelFromObjStr(obj.Child)+'" type="revolute">\n')
  File "/home/suraj/.FreeCAD/Mod/RobotCreator/Macros/sdfExport.FCMacro", line 22, in bodyLabelFromObjStr
    return c.Label
<class 'AttributeError'>: 'NoneType' object has no attribute 'Label'
`

**Comment by realteck-ky** [comment]
Have you used assembly plugins like Assembly2, 3, 4 and A2plus?
RobotCreator Workbench cannot read those parametric object now.

More detail, it is caused from parent and children object parsing.
`obj.TypeId == 'PartDesign::Body'` in `bodyFromPad()` may be worse.
It needs to fix the object parsing function to handle parametric information such assembly plugins.
